services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-videos
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - "27017:27017"